#!/bin/bash
# =========================
# Systemd 工具库
# 提供 systemd 服务管理相关操作
# =========================

# 判断 systemd 是否可用
systemd_ready() {
  command -v systemctl >/dev/null 2>&1 || return 1
  systemctl show --property=Version --value >/dev/null 2>&1 || return 1
  return 0
}

# 等待 config.yaml 出现并写入 secret
wait_secret_ready() {
  local conf_file="$1"
  local timeout_sec="${2:-6}"

  local end=$((SECONDS + timeout_sec))
  while [ "$SECONDS" -lt "$end" ]; do
    if [ -s "$conf_file" ] && grep -qE '^[[:space:]]*secret:' "$conf_file"; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

# 安装 profile.d 代理快捷命令
install_profiled() {
  local install_dir="$1"
  local http_port="${2:-7890}"
  local socks_port="${3:-7891}"
  local profiled_file="${4:-/etc/profile.d/clash-for-linux.sh}"

  # 处理 auto 端口
  [ "$http_port" = "auto" ] && http_port="7890"
  [ "$socks_port" = "auto" ] && socks_port="7891"

  tee "$profiled_file" >/dev/null <<EOF
# Clash for Linux proxy helpers
# Auto-generated by clash-for-linux installer.

# Project directory
export CLASH_DIR="${install_dir}"

# Default proxy endpoint (HTTP)
export CLASH_HTTP_PROXY="http://127.0.0.1:${http_port}"
# Default proxy endpoint (SOCKS5)
export CLASH_SOCKS_PROXY="socks5://127.0.0.1:${socks_port}"

proxy_on() {
  export http_proxy="\$CLASH_HTTP_PROXY"
  export https_proxy="\$CLASH_HTTP_PROXY"
  export all_proxy="\$CLASH_SOCKS_PROXY"
  export HTTP_PROXY="\$CLASH_HTTP_PROXY"
  export HTTPS_PROXY="\$CLASH_HTTP_PROXY"
  export ALL_PROXY="\$CLASH_SOCKS_PROXY"
  echo "[OK] Proxy enabled: \$CLASH_HTTP_PROXY"
}

proxy_down() {
  unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY
  echo "[OK] Proxy disabled"
}

proxy_status() {
  echo "http_proxy=\${http_proxy:-<empty>}"
  echo "https_proxy=\${https_proxy:-<empty>}"
  echo "all_proxy=\${all_proxy:-<empty>}"
}

# 快速跳转别名
alias proxy="cd \$CLASH_DIR"

# 简化别名（带连字符）
alias proxy-on='source /etc/profile.d/clash-for-linux.sh && proxy_on'
alias proxy-down='source /etc/profile.d/clash-for-linux.sh && proxy_down'
EOF

  chmod 644 "$profiled_file"
}
